name: Build Pack
on:
  push:
    branches:
      - main 
jobs:
  pack: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        yarn add electron-builder --dev
        npm install -g electron-builder
        electron-builder --win portable

    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: packs 
